"use client";
import {useEffect,useState} from "react";
import memory from "../../data/memory.json";

type R={id:string;type:string;title:string;detail:string;date:string};
export default function Memory(){
 const p:any=(memory as any).projects?.Buildalong; const [rs,setRs]=useState<R[]>([]); const [type,setType]=useState("Learning"); const [title,setTitle]=useState(""); const [detail,setDetail]=useState("");
 useEffect(()=>{try{const x=localStorage.getItem("umbrella-intelligence-memory");if(x)setRs(JSON.parse(x))}catch{}} ,[]);
 const add=()=>{if(!title.trim()||!detail.trim())return;const r={id:crypto.randomUUID(),type,title,detail,date:new Date().toISOString().slice(0,10)};const n=[r,...rs];setRs(n);localStorage.setItem("umbrella-intelligence-memory",JSON.stringify(n));setTitle("");setDetail("")};
 return <main className="shell"><section className="main" style={{maxWidth:1050,margin:"0 auto",padding:"32px 20px"}}><a href="/">← Umbrella Intelligence</a><div className="hero" style={{marginTop:24}}><div className="eyebrow">Persistent project memory</div><h1>Buildalong</h1><p>{p?.purpose}</p><strong>{p?.current_stage}</strong><div className="card" style={{marginTop:18}}><b>Validation rule</b><p>{p?.validation_gate}</p></div></div><div className="section-title"><h2>Buildalong process</h2><span className="hint">Path to real-world validation</span></div><div className="card">{(p?.process||[]).map((x:string,i:number)=><div className="step" key={x}><b>{i+1}</b><span>{x}</span></div>)}</div><div className="section-title"><h2>Save project memory</h2><span className="hint">Durable lessons, decisions and test results</span></div><div className="card form"><div className="formRow"><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option>Learning</option><option>Decision</option><option>Test result</option><option>Failure</option><option>Next step</option></select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What should we remember?"/></label></div><label>Detail<textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Record the useful, durable information..."/></label><button className="save" onClick={add}>Save to project memory</button><p className="localNote">New entries are currently stored in this browser; the validated seed memory is versioned in the repository.</p></div>{rs.length>0&&<><div className="section-title"><h2>Captured memory</h2></div>{rs.map(r=><article className="card record" key={r.id}><div className="recordHead"><div><span className="pill blue">{r.type}</span><h3>{r.title}</h3></div><span>{r.date}</span></div><p>{r.detail}</p></article>)}</>}<div className="section-title"><h2>Stored Buildalong notes</h2></div><div className="card">{(p?.notes||[]).map((x:string)=><div className="item" key={x}>{x}</div>)}</div></section></main>
}
